# Quantitative Momentum Strategy

At a very grassroot level, "Momentum investing" refers to investing in stocks that have shown price increases the most in a past timeframe.

This project is going to have an investing strategy that selects the 50 stocks with the highest price momentum. From there, recommended trades for an equal-weight portfolio of these 50 stocks will be calculated.


## Library Imports

The first thing to do is import the open-source software libraries that will be used.

In [1]:
import numpy as np
import pandas as pd
import requests
import math
from scipy.stats import percentileofscore as score
import xlsxwriter

## Importing Our List of Stocks

A list of stocks and an API token needs to be imported before proceeding.

In [2]:
stocks = pd.read_csv('sp_500_stocks.csv')
from secrets import IEX_CLOUD_API_TOKEN

## Making the First API Call

To make the first version of a momentum screener, one-year price returns for every stock is needed.

In [4]:
symbol = 'AAPL'
api_url = f'https://sandbox.iexapis.com/stable/stock/{symbol}/stats?token={IEX_CLOUD_API_TOKEN}'
data = requests.get(api_url).json()
data

{'companyName': 'Apple Inc',
 'marketcap': 2588496318287,
 'week52high': 169.4,
 'week52low': 119.9,
 'week52highSplitAdjustOnly': 172,
 'week52lowSplitAdjustOnly': 118.92,
 'week52change': 0.3669443064648631,
 'sharesOutstanding': 16502259768,
 'float': 0,
 'avg10Volume': 92762770,
 'avg30Volume': 76917336,
 'day200MovingAvg': 150.1,
 'day50MovingAvg': 154.26,
 'employees': 152853,
 'ttmEPS': 11.44,
 'ttmDividendRate': 0.8762997517101159,
 'dividendYield': 0.005563865435013969,
 'nextDividendDate': '',
 'exDividendDate': '2021-10-29',
 'nextEarningsDate': '2022-01-21',
 'peRatio': 14.13838268259807,
 'beta': 1.4692198388307858,
 'maxChangePercent': 59.91475100455038,
 'year5ChangePercent': 5.080544235905614,
 'year2ChangePercent': 1.44019353407238,
 'year1ChangePercent': 0.3706517288974013,
 'ytdChangePercent': 0.1916008962588575,
 'month6ChangePercent': 0.2675715302500085,
 'month3ChangePercent': 0.0582062545982718,
 'month1ChangePercent': 0.03057354009064221,
 'day30ChangePercent': 0.04876099601816906,
 'day5ChangePercent': -0.02347215485564475}

## Parsing the API Call

This API call has all the required information.

In [5]:
data['year1ChangePercent']

0.3706517288974013

## Executing A Batch API Call & Building the DataFrame

t's now time to execute several batch API calls and add the information needed to the DataFrame.

The following code cell contains some code already built that can be re-used for this project. More specifically, it contains a function called chunks that can be used to divide a list of securities into groups of 100.

In [6]:
def chunks(lst, n):
    for i in range(0, len(lst), n):
        yield lst[i:i + n]   
        
symbol_groups = list(chunks(stocks['Ticker'], 100))
symbol_strings = []
for i in range(0, len(symbol_groups)):
    symbol_strings.append(','.join(symbol_groups[i]))
#     print(symbol_strings[i])

my_columns = ['Ticker', 'Price', 'One-Year Price Return', 'Number of Shares to Buy']

Now, data needs to be added to a blank data frame one-by-one.

In [7]:
final_dataframe = pd.DataFrame(columns = my_columns)

for symbol_string in symbol_strings:
    batch_api_call_url = f'https://sandbox.iexapis.com/stable/stock/market/batch/?symbols={symbol_string}&types=price,stats&token={IEX_CLOUD_API_TOKEN}'
    data = requests.get(batch_api_call_url).json()
    for symbol in symbol_string.split(','):
         final_dataframe = final_dataframe.append(
             pd.Series(
                 [
                     symbol, 
                     data[symbol]['price'],
                     data[symbol]['stats']['year1ChangePercent'],
                     'N/A'
                 ], 
                 index = my_columns
             ), 
             ignore_index = True
         )
final_dataframe

    Ticker   Price One-Year Price Return Number of Shares to Buy
0        A  156.87              0.344616                     N/A
1      AAL   18.32              0.187601                     N/A
2      AAP  233.44              0.547262                     N/A
3     AAPL  160.88              0.359804                     N/A
4     ABBV  120.90              0.168086                     N/A
..     ...     ...                   ...                     ...
500    YUM  127.37               0.18348                     N/A
501    ZBH  128.00             -0.165128                     N/A
502   ZBRA  627.50              0.571535                     N/A
503   ZION   65.40              0.686075                     N/A
504    ZTS  226.17              0.366437                     N/A

[505 rows x 4 columns]

## Removing Low-Momentum Stocks

The investment strategy that this project aims to build seeks to identify the 50 highest-momentum stocks in the S&P 500.

So, all the stocks in the DataFrame that fall below this momentum threshold need to be removed.

In [8]:
final_dataframe.sort_values('One-Year Price Return', ascending = False, inplace = True)
final_dataframe = final_dataframe[:51]
final_dataframe.reset_index(drop = True, inplace = True)
final_dataframe

   Ticker    Price One-Year Price Return Number of Shares to Buy
0      LB    82.65              2.332291                     N/A
1     DVN    44.06              2.017648                     N/A
2    FTNT   353.50              1.651769                     N/A
3     MRO    16.13               1.56269                     N/A
4    FANG   112.13              1.521952                     N/A
5    MCHP    85.10              1.504918                     N/A
6    NVDA   335.20              1.391486                     N/A
7       F    20.38              1.188911                     N/A
8     NUE   113.61              1.162783                     N/A
9      IT   335.00              1.125495                     N/A
10   SIVB   758.40              1.053198                     N/A
11    SPG   167.69              0.991527                     N/A
12    ALB   276.42              0.985851                     N/A
13   INTU   711.23              0.915018                     N/A
14    EXR   205.59               0.88405                     N/A
15    IRM    49.15              0.875786                     N/A
16   DXCM   586.20              0.868468                     N/A
17    AIV     7.78              0.861841                     N/A
18   ANET   126.80              0.854144                     N/A
19    OKE    62.68              0.829784                     N/A
20    RHI   118.78              0.807137                     N/A
21    OXY    31.09              0.806625                     N/A
22    LLY   263.42              0.805407                     N/A
23    AMD   164.50              0.775551                     N/A
24   AMAT   155.98              0.759963                     N/A
25   ODFL   373.44              0.754552                     N/A
26    COP    74.02              0.754271                     N/A
27    EOG    92.31              0.748996                     N/A
28    COF   148.00               0.74851                     N/A
29    JCI    81.39              0.746399                     N/A
30    CMA    89.23              0.743522                     N/A
31    WFC    51.18              0.738645                     N/A
32    EFX   291.17              0.723821                     N/A
33   NTAP    93.63              0.717578                     N/A
34    PXD   184.61              0.715203                     N/A
35    PWR   124.82              0.701239                     N/A
36    MAA   218.00              0.688898                     N/A
37     GS   387.83              0.688167                     N/A
38   ZION    65.40              0.686075                     N/A
39     CF    64.86              0.684489                     N/A
40   FITB    43.49              0.681755                     N/A
41   TSCO   232.20              0.676369                     N/A
42   XLNX   243.59              0.650168                     N/A
43    RJF   104.79              0.645379                     N/A
44   NDAQ   214.74              0.643801                     N/A
45    FRC   216.91              0.638551                     N/A
46   KEYS   198.31              0.637382                     N/A
47    LKQ    60.20               0.63599                     N/A
48    AZO  1863.35              0.633883                     N/A
49    KSS    55.07               0.63318                     N/A
50    LOW   258.01              0.632159                     N/A

## Calculating the Number of Shares to Buy

Next, the number of shares to buy needs to be calculated.

In [9]:
def portfolio_input():
    global portfolio_size
    portfolio_size = input('Enter the size of your portfolio: ')
    
    try:
        float(portfolio_size)
    except ValueError:
        print('Must enter a number. \nPlease enter a number.')
        portfolio_size = input('Enter the size of your portfolio: ')
        
portfolio_input()
print(portfolio_size)

Enter the size of your portfolio: 10000000
10000000

In [25]:
position_size = float(portfolio_size)/len(final_dataframe.index)
for i in range(0, len(final_dataframe)):
    final_dataframe.loc[i, 'Number of Shares to Buy'] = math.floor(position_size/final_dataframe.loc[i, 'Price'])
    
final_dataframe

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/core/indexing.py:1817: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

   Ticker    Price One-Year Price Return Number of Shares to Buy
0      LB    82.65              2.332291                     237
1     DVN    44.06              2.017648                     445
2    FTNT   353.50              1.651769                      55
3     MRO    16.13               1.56269                    1215
4    FANG   112.13              1.521952                     174
5    MCHP    85.10              1.504918                     230
6    NVDA   335.20              1.391486                      58
7       F    20.38              1.188911                     962
8     NUE   113.61              1.162783                     172
9      IT   335.00              1.125495                      58
10   SIVB   758.40              1.053198                      25
11    SPG   167.69              0.991527                     116
12    ALB   276.42              0.985851                      70
13   INTU   711.23              0.915018                      27
14    EXR   205.59               0.88405                      95
15    IRM    49.15              0.875786                     398
16   DXCM   586.20              0.868468                      33
17    AIV     7.78              0.861841                    2520
18   ANET   126.80              0.854144                     154
19    OKE    62.68              0.829784                     312
20    RHI   118.78              0.807137                     165
21    OXY    31.09              0.806625                     630
22    LLY   263.42              0.805407                      74
23    AMD   164.50              0.775551                     119
24   AMAT   155.98              0.759963                     125
25   ODFL   373.44              0.754552                      52
26    COP    74.02              0.754271                     264
27    EOG    92.31              0.748996                     212
28    COF   148.00               0.74851                     132
29    JCI    81.39              0.746399                     240
30    CMA    89.23              0.743522                     219
31    WFC    51.18              0.738645                     383
32    EFX   291.17              0.723821                      67
33   NTAP    93.63              0.717578                     209
34    PXD   184.61              0.715203                     106
35    PWR   124.82              0.701239                     157
36    MAA   218.00              0.688898                      89
37     GS   387.83              0.688167                      50
38   ZION    65.40              0.686075                     299
39     CF    64.86              0.684489                     302
40   FITB    43.49              0.681755                     450
41   TSCO   232.20              0.676369                      84
42   XLNX   243.59              0.650168                      80
43    RJF   104.79              0.645379                     187
44   NDAQ   214.74              0.643801                      91
45    FRC   216.91              0.638551                      90
46   KEYS   198.31              0.637382                      98
47    LKQ    60.20               0.63599                     325
48    AZO  1863.35              0.633883                      10
49    KSS    55.07               0.63318                     356
50    LOW   258.01              0.632159                      75

## Building a Better (and More Realistic) Momentum Strategy

Real-world quantitative investment firms differentiate between "high quality" and "low quality" momentum stocks:

* High-quality momentum stocks show "slow and steady" outperformance over long periods of time
* Low-quality momentum stocks might not show any momentum for a long time, and then surge upwards.

The reason why high-quality momentum stocks are preferred is because low-quality momentum can often be cause by short-term news that is unlikely to be repeated in the future (such as an FDA approval for a biotechnology company).

To identify high-quality momentum, we're going to build a strategy that selects stocks from the highest percentiles of: 

* 1-month price returns
* 3-month price returns
* 6-month price returns
* 1-year price returns

The abbreviation `hqm` often stands for `high-quality momentum`.

In [26]:
 hqm_columns = [
     'Ticker',
     'Price',
     'Number of Shares to Buy',
     'One-Year Price Return',
     'One-Year Return Percentile',
     'Six-Month Price Return',
     'Six-Month Return Percentile',
     'Three-Month Price Return',
     'Three-Month Return Percentile',
     'One-Month Price Return',
     'One-Month Return Percentile',
     'HQM Score'
 ]
    
hqm_dataframe = pd.DataFrame(columns = hqm_columns)

for symbol_string in symbol_strings:
    batch_api_call_url = f'https://sandbox.iexapis.com/stable/stock/market/batch/?symbols={symbol_string}&types=price,stats&token={IEX_CLOUD_API_TOKEN}'
    data = requests.get(batch_api_call_url).json()
    for symbol in symbol_string.split(','):
        hqm_dataframe = hqm_dataframe.append(
            pd.Series(
            [
                symbol,
                data[symbol]['price'],
                'N/A',
                data[symbol]['stats']['year1ChangePercent'],
                'N/A',
                data[symbol]['stats']['month6ChangePercent'],
                'N/A',
                data[symbol]['stats']['month3ChangePercent'],
                'N/A',
                data[symbol]['stats']['month1ChangePercent'],
                'N/A',
                'N/A'
            ],
                index = hqm_columns
            ),
            ignore_index = True
        
        )
hqm_dataframe

,Ticker,Price,Number of Shares to Buy,One-Year Price Return,One-Year Return Percentile,Six-Month Price Return,Six-Month Return Percentile,Three-Month Price Return,Three-Month Return Percentile,One-Month Price Return,One-Month Return Percentile,HQM Score
0,A,156.04,N/A,0.354359,N/A,0.105264,N/A,-0.125512,N/A,-0.024066,N/A,N/A
1,AAL,18.16,N/A,0.18682,N/A,-0.272982,N/A,-0.128236,N/A,-0.075634,N/A,N/A
2,AAP,229.87,N/A,0.533743,N/A,0.207903,N/A,0.122241,N/A,0.007955,N/A,N/A
3,AAPL,167.46,N/A,0.370301,N/A,0.263445,N/A,0.057965,N/A,0.029574,N/A,N/A
4,ABBV,122.53,N/A,0.169847,N/A,0.055357,N/A,-0.01406,N/A,0.063361,N/A,N/A
...,...,...,...,...,...,...,...,...,...,...,...,...
500,YUM,129.54,N/A,0.180956,N/A,0.043751,N/A,-0.055557,N/A,-0.009572,N/A,N/A
501,ZBH,124.10,N/A,-0.159926,N/A,-0.252058,N/A,-0.1644,N/A,-0.138238,N/A,N/A
502,ZBRA,608.50,N/A,0.582308,N/A,0.189485,N/A,0.004724,N/A,0.111074,N/A,N/A
503,ZION,67.12,N/A,0.698432,N/A,0.128443,N/A,0.104987,N/A,0.027154,N/A,N/A
504,ZTS,225.88,N/A,0.36618,N/A,0.254685,N/A,0.080934,N/A,0.032368,N/A,N/A

## Calculating Momentum Percentiles

Momentum percentile scores for every stock will now be calculated. More specifically, the calculated numbers will be percentile scores for the following metrics for every stock:

* `One-Year Price Return`
* `Six-Month Price Return`
* `Three-Month Price Return`
* `One-Month Price Return`

In [27]:
time_periods = [
    'One-Year',
    'Six-Month',
    'Three-Month',
    'One-Month'
]

for row in hqm_dataframe.index:
    for time_period in time_periods:
        change_col = f'{time_period} Price Return'
        percentile_col = f'{time_period} Return Percentile'
        hqm_dataframe = hqm_dataframe.fillna(value = np.nan)
        hqm_dataframe.loc[row, percentile_col] = (score(hqm_dataframe[change_col], hqm_dataframe.loc[row, change_col]))/100
hqm_dataframe

,Ticker,Price,Number of Shares to Buy,One-Year Price Return,One-Year Return Percentile,Six-Month Price Return,Six-Month Return Percentile,Three-Month Price Return,Three-Month Return Percentile,One-Month Price Return,One-Month Return Percentile,HQM Score
0,A,156.04,N/A,0.354359,0.633663,0.105264,0.675248,-0.125512,0.126733,-0.024066,0.39802,N/A
1,AAL,18.16,N/A,0.186820,0.427723,-0.272982,0.035644,-0.128236,0.116832,-0.075634,0.142574,N/A
2,AAP,229.87,N/A,0.533743,0.815842,0.207903,0.839604,0.122241,0.877228,0.007955,0.615842,N/A
3,AAPL,167.46,N/A,0.370301,0.653465,0.263445,0.889109,0.057965,0.722772,0.029574,0.734653,N/A
4,ABBV,122.53,N/A,0.169847,0.388119,0.055357,0.570297,-0.014060,0.437624,0.063361,0.859406,N/A
...,...,...,...,...,...,...,...,...,...,...,...,...
500,YUM,129.54,N/A,0.180956,0.411881,0.043751,0.542574,-0.055557,0.293069,-0.009572,0.508911,N/A
501,ZBH,124.10,N/A,-0.159926,0.043564,-0.252058,0.041584,-0.164400,0.073267,-0.138238,0.037624,N/A
502,ZBRA,608.50,N/A,0.582308,0.859406,0.189485,0.809901,0.004724,0.526733,0.111074,0.954455,N/A
503,ZION,67.12,N/A,0.698432,0.922772,0.128443,0.722772,0.104987,0.853465,0.027154,0.724752,N/A
504,ZTS,225.88,N/A,0.366180,0.649505,0.254685,0.883168,0.080934,0.794059,0.032368,0.758416,N/A

## Calculating the HQM Score

The `HQM Score` will now be calculated which is the high-quality momentum score used to filter for stocks in this investing strategy.

The `HQM Score` will be the arithmetic mean of the 4 momentum percentile scores previously calculated.

In [28]:
# To calculate arithmetic mean, the `mean` function from Python's built-in `statistics` module is used.
from statistics import mean

for row in hqm_dataframe.index:
    momentum_percentiles = []
    for time_period in time_periods:
        momentum_percentiles.append(hqm_dataframe.loc[row, f'{time_period} Return Percentile'])
    hqm_dataframe.loc[row, 'HQM Score'] = mean(momentum_percentiles)

hqm_dataframe

,Ticker,Price,Number of Shares to Buy,One-Year Price Return,One-Year Return Percentile,Six-Month Price Return,Six-Month Return Percentile,Three-Month Price Return,Three-Month Return Percentile,One-Month Price Return,One-Month Return Percentile,HQM Score
0,A,156.04,N/A,0.354359,0.633663,0.105264,0.675248,-0.125512,0.126733,-0.024066,0.39802,0.458416
1,AAL,18.16,N/A,0.186820,0.427723,-0.272982,0.035644,-0.128236,0.116832,-0.075634,0.142574,0.180693
2,AAP,229.87,N/A,0.533743,0.815842,0.207903,0.839604,0.122241,0.877228,0.007955,0.615842,0.787129
3,AAPL,167.46,N/A,0.370301,0.653465,0.263445,0.889109,0.057965,0.722772,0.029574,0.734653,0.75
4,ABBV,122.53,N/A,0.169847,0.388119,0.055357,0.570297,-0.014060,0.437624,0.063361,0.859406,0.563861
...,...,...,...,...,...,...,...,...,...,...,...,...
500,YUM,129.54,N/A,0.180956,0.411881,0.043751,0.542574,-0.055557,0.293069,-0.009572,0.508911,0.439109
501,ZBH,124.10,N/A,-0.159926,0.043564,-0.252058,0.041584,-0.164400,0.073267,-0.138238,0.037624,0.04901
502,ZBRA,608.50,N/A,0.582308,0.859406,0.189485,0.809901,0.004724,0.526733,0.111074,0.954455,0.787624
503,ZION,67.12,N/A,0.698432,0.922772,0.128443,0.722772,0.104987,0.853465,0.027154,0.724752,0.805941
504,ZTS,225.88,N/A,0.366180,0.649505,0.254685,0.883168,0.080934,0.794059,0.032368,0.758416,0.771287

## Selecting the 50 Best Momentum Stocks

he 50 best momentum stocks are identified by sorting the DataFrame on the HQM Score column and dropping all but the top 50 entries.

In [1]:
hqm_dataframe.sort_values('HQM Score', ascending = False, inplace = True)
hqm_dataframe = hqm_dataframe[:50]
hqm_dataframe.reset_index(inplace = True, drop = True)
hqm_dataframe

NameError: name 'hqm_dataframe' is not defined

## Calculating the Number of Shares to Buy

In [30]:
portfolio_input()

Enter the size of your portfolio: 1000000

In [31]:
position_size = float(portfolio_size)/len(hqm_dataframe.index)
for i in hqm_dataframe.index:
    hqm_dataframe.loc[i, 'Number of Shares to Buy'] = math.floor(position_size/hqm_dataframe.loc[i,'Price']) 
hqm_dataframe

NameError: name 'portfolio_size' is not defined

## Formatting the Excel Output

The XlsxWriter library for Python will be used to create well-formatted Excel files.

In [32]:
writer = pd.ExcelWriter('momentum_strategy.xlsx', engine='xlsxwriter')
hqm_dataframe.to_excel(writer, sheet_name='Momentum Strategy', index = False)

## Creating the Formats We'll needed for the .xlsx File

Four main formats are needed for the Excel document:

* String format for tickers
* \$XX.XX format for stock prices
* \$XX,XXX format for market capitalization
* Integer format for the number of shares to purchase

In [33]:
background_color = '#0a0a23'
font_color = '#ffffff'

string_template = writer.book.add_format(
        {
            'font_color': font_color,
            'bg_color': background_color,
            'border': 1
        }
    )

dollar_template = writer.book.add_format(
        {
            'num_format':'$0.00',
            'font_color': font_color,
            'bg_color': background_color,
            'border': 1
        }
    )

integer_template = writer.book.add_format(
        {
            'num_format':'0',
            'font_color': font_color,
            'bg_color': background_color,
            'border': 1
        }
    )

percent_template = writer.book.add_format(
        {
            'num_format':'0.0%',
            'font_color': font_color,
            'bg_color': background_color,
            'border': 1
        }
    )

In [34]:
column_formats = { 
                    'A': ['Ticker', string_template],
                    'B': ['Price', dollar_template],
                    'C': ['Number of Shares to Buy', integer_template],
                    'D': ['One-Year Price Return', percent_template],
                    'E': ['One-Year Return Percentile', percent_template],
                    'F': ['Six-Month Price Return', percent_template],
                    'G': ['Six-Month Return Percentile', percent_template],
                    'H': ['Three-Month Price Return', percent_template],
                    'I': ['Three-Month Return Percentile', percent_template],
                    'J': ['One-Month Price Return', percent_template],
                    'K': ['One-Month Return Percentile', percent_template],
                    'L': ['HQM Score', percent_template]
}

for column in column_formats.keys():
    writer.sheets['Momentum Strategy'].set_column(f'{column}:{column}', 25, column_formats[column][1])
    writer.sheets['Momentum Strategy'].write(f'{column}1', column_formats[column][0], string_template)

## Saving the Excel Output

In [35]:
writer.save()